// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHTHQtPdc3GnT6nxdQ6mlRDThyxnu8JY',
    appId: '1:1030673247593:web:d4f6e8d9cbd7c481a421f8',
    messagingSenderId: '1030673247593',
    projectId: 'project1-dde8e',
    authDomain: 'project1-dde8e.firebaseapp.com',
    storageBucket: 'project1-dde8e.firebasestorage.app',
    measurementId: 'G-DYWD0MQ7MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCit7_rawgCUiGVS_M0RLd2qQpRzCLcAFw',
    appId: '1:1030673247593:android:da952276a22207f6a421f8',
    messagingSenderId: '1030673247593',
    projectId: 'project1-dde8e',
    storageBucket: 'project1-dde8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAya3JxeNl8YsaQGC4nL0LAF8muirdXgbw',
    appId: '1:1030673247593:ios:48bddefd5f1da012a421f8',
    messagingSenderId: '1030673247593',
    projectId: 'project1-dde8e',
    storageBucket: 'project1-dde8e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAya3JxeNl8YsaQGC4nL0LAF8muirdXgbw',
    appId: '1:1030673247593:ios:48bddefd5f1da012a421f8',
    messagingSenderId: '1030673247593',
    projectId: 'project1-dde8e',
    storageBucket: 'project1-dde8e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHTHQtPdc3GnT6nxdQ6mlRDThyxnu8JY',
    appId: '1:1030673247593:web:181c6d3e05da4435a421f8',
    messagingSenderId: '1030673247593',
    projectId: 'project1-dde8e',
    authDomain: 'project1-dde8e.firebaseapp.com',
    storageBucket: 'project1-dde8e.firebasestorage.app',
    measurementId: 'G-XJVKGBCPRC',
  );

}